### ISSUE TITLE
The desired archetype does not exist (org.uberfire:uberfire-project-archetype:0.5.0-SNAPSHOT

### ISSUE THREAD

**Issue by bennob** [uberfire/uberfire-docs#1]
Hello

I try to get started with Uberfire (cool project!), but I have trouble with the 5 minutes tutorial.

From:
https://github.com/uberfire/uberfire-docs/blob/master/docs/gettingStarted/5minIntroduction.md

executing:
$ mvn archetype:generate -DarchetypeGroupId=org.uberfire -DarchetypeArtifactId=uberfire-project-archetype -DarchetypeVersion=0.5.0-SNAPSHOT

Results in:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.2:generate (default-cli) on project standalone-pom: The desired archetype does not exist (org.uberfire:uberfire-project-archetype:0.5.0-SNAPSHOT) -> [Help 1]

It works with 04.2.CR2: The newest version here http://mvnrepository.com/artifact/org.uberfire/uberfire-project-archetype

benno ~>$ mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.7.0_71, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"

**Comment by ederign** [comment]
Hi bennob,

Sorry about it. We will release 0.5.x updated version on Monday.

But right now, if you want to try if uberfire you can build this archetype from source.

git clone git@github.com:uberfire/uberfire.git
git checkout -t origin/0.5.x
cd uberfire-archetype
mvn clean install

Sorry about it, we are still working on docs and this new release.

Fell free to ping me on #uberfire (freenode) to further questions.

Best regards.

**Comment by ederign** [comment]
bennob we have made a huge upgrade in docs. Please take a look!
